import type { ActivityType, TaskPriority, TaskStatus } from "@/modules/activities/types/types";
import type { ApplicationStage } from "@/modules/applications/applicationForm.types";

export type DashboardDataSource = "mock" | "live";

/** Standard wrapper for every dashboard service response. */
export interface DashboardServiceResponse<TData> {
  /** Payload for the requested dashboard widget or collection. */
  data: TData;
  /** ISO timestamp generated by the service layer. */
  generatedAt: string;
  /** Identifies whether the response came from backend APIs or temporary mock data. */
  source: DashboardDataSource;
}

/** Lightweight user reference used for ownership, assignment, and activity actor fields. */
export interface DashboardUserReferenceDto {
  id: string;
  name: string;
  role?: string;
}

/** Lead summary required by dashboard KPIs and action points. */
export interface DashboardLeadDto {
  id: string;
  tenantId: string;
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  isArchived: boolean;
  leadStage: "New" | "Contacted" | "Qualified" | "Prospective" | "Lost" | "Enrolled" | string;
  assignedTo: DashboardUserReferenceDto | null;
  sourceName: string;
  score: number | null;
  destinationCountries: string[];
  lastActivityAt: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Application summary required by dashboard KPIs and review action points. */
export interface DashboardApplicationDto {
  id: string;
  leadId?: string;
  studentName: string;
  email: string;
  phone: string;
  targetCountry: string;
  targetUniversity: string;
  course: string;
  intakeMonth: string;
  intakeYear: number;
  stage: ApplicationStage;
  owner: DashboardUserReferenceDto | null;
  createdAt: string;
  updatedAt: string;
}

/** Task summary row used for dashboard workload and overdue calculations. */
export interface DashboardTaskDto {
  id: string;
  title: string;
  description: string;
  priority: TaskPriority;
  status: TaskStatus;
  dueDate: string;
  assignedTo: DashboardUserReferenceDto | null;
  linkedEntity: {
    id: string | null;
    name: string;
    type: "LEAD" | "APPLICATION" | "STUDENT" | "GENERAL";
  };
  createdAt: string;
  completedAt?: string | null;
}

/** Aggregate task counters used by admin and activity-manager dashboard cards. */
export interface DashboardTaskSummaryDto {
  completed: number;
  dueToday: number;
  inProgress: number;
  overdue: number;
  pending: number;
  total: number;
}

export type DashboardKpiAccent = "blue" | "green" | "red" | "orange" | "purple";

export type DashboardDeltaTone = "up" | "down" | "flat";

/** Role-specific KPI card shown at the top of the dashboard. */
export interface DashboardKpiDto {
  accent: DashboardKpiAccent;
  delta: string;
  deltaTone: DashboardDeltaTone;
  icon: string;
  label: string;
  value: string;
}

/** Quick action button in the dashboard greeting section. */
export interface DashboardQuickAction {
  href: string;
  icon: string;
  label: string;
}

/** Controls which dashboard widgets are visible for a role profile. */
export interface DashboardWidgetVisibility {
  applicationPipeline: boolean;
  leadPipeline: boolean;
  performance: boolean;
  recentActivities: boolean;
  weeklyActivity: boolean;
}

/** Single stage in the lead or application pipeline visualization. */
export interface DashboardPipelineStageDto {
  color: string;
  count: number;
  label: string;
}

/** Lead pipeline summary — GET /api/dashboard/pipeline/leads */
export interface DashboardLeadPipelineDto {
  stages: DashboardPipelineStageDto[];
  total: number;
}

/** Application pipeline summary — GET /api/dashboard/pipeline/applications */
export interface DashboardApplicationPipelineDto {
  stages: DashboardPipelineStageDto[];
  total: number;
}

/** Weekly activity chart point — GET /api/dashboard */
export interface DashboardActivityChartPointDto {
  activities: number;
  label: string;
  tasks: number;
}

/** Performance metric bar — GET /api/dashboard */
export interface DashboardPerformanceMetricDto {
  color: string;
  label: string;
  unit?: string;
  value: number;
}

/** Recent activity item shown in the dashboard operational pulse. */
export interface DashboardActivityDto {
  id: string;
  type: ActivityType;
  title: string;
  description: string;
  status: "Completed" | "Scheduled" | "Sent" | "Internal" | "Contract" | string;
  occurredAt: string;
  actor: DashboardUserReferenceDto | null;
  linkedEntity: {
    id: string | null;
    name: string;
    type: "LEAD" | "APPLICATION" | "STUDENT" | "GENERAL";
  };
  durationMinutes?: number;
}
