import type { ActivityType, TaskPriority, TaskStatus } from "@/modules/activities/types/types";
import type { ApplicationStage } from "@/modules/applications/applicationForm.types";

export type DashboardDataSource = "mock" | "live";

/** Standard wrapper for every dashboard service response. */
export interface DashboardServiceResponse<TData> {
  /** Payload for the requested dashboard widget or collection. */
  data: TData;
  /** ISO timestamp generated by the service layer. */
  generatedAt: string;
  /** Identifies whether the response came from backend APIs or temporary mock data. */
  source: DashboardDataSource;
}

/** Lightweight user reference used for ownership, assignment, and activity actor fields. */
export interface DashboardUserReferenceDto {
  id: string;
  name: string;
  role?: string;
}

/** Lead summary required by dashboard KPIs and action points. */
export interface DashboardLeadDto {
  id: string;
  tenantId: string;
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  isArchived: boolean;
  leadStage: "New" | "Contacted" | "Qualified" | "Lost" | "Converted" | string;
  assignedTo: DashboardUserReferenceDto | null;
  sourceName: string;
  score: number | null;
  destinationCountries: string[];
  lastActivityAt: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Application summary required by dashboard KPIs and review action points. */
export interface DashboardApplicationDto {
  id: string;
  leadId?: string;
  studentName: string;
  email: string;
  phone: string;
  targetCountry: string;
  targetUniversity: string;
  course: string;
  intakeMonth: string;
  intakeYear: number;
  stage: ApplicationStage;
  owner: DashboardUserReferenceDto | null;
  createdAt: string;
  updatedAt: string;
}

/** Task summary row used for dashboard workload and overdue calculations. */
export interface DashboardTaskDto {
  id: string;
  title: string;
  description: string;
  priority: TaskPriority;
  status: TaskStatus;
  dueDate: string;
  assignedTo: DashboardUserReferenceDto | null;
  linkedEntity: {
    id: string | null;
    name: string;
    type: "LEAD" | "APPLICATION" | "STUDENT" | "GENERAL";
  };
  createdAt: string;
  completedAt?: string | null;
}

/** Aggregate task counters used by admin and activity-manager dashboard cards. */
export interface DashboardTaskSummaryDto {
  completed: number;
  dueToday: number;
  inProgress: number;
  overdue: number;
  pending: number;
  total: number;
}

/** Recent activity item shown in the dashboard operational pulse. */
export interface DashboardActivityDto {
  id: string;
  type: ActivityType;
  title: string;
  description: string;
  status: "Completed" | "Scheduled" | "Sent" | "Internal" | "Contract" | string;
  occurredAt: string;
  actor: DashboardUserReferenceDto | null;
  linkedEntity: {
    id: string | null;
    name: string;
    type: "LEAD" | "APPLICATION" | "STUDENT" | "GENERAL";
  };
  durationMinutes?: number;
}
