import type { Agency } from "@/modules/super-admin/superAdmin.types";

export const mockAgencies: Agency[] = [
  {
    id: "agency-001",
    name: "Arpan Consultancy",
    registrationId: "U74999TG2020PTC123456",
    address: "12 MG Road",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    status: "active",
    verificationStatus: "verified",
    subscriptionPlan: "professional",
    trialEndsAt: null,
    subscriptionEndsAt: "2026-12-31",
    userCount: 18,
    studentCount: 342,
    leadCount: 1280,
    applicationCount: 456,
    createdAt: "2024-03-15T10:00:00Z",
    admin: {
      firstName: "Ravi",
      lastName: "Sharma",
      email: "ravi@arpanconsultancy.com",
      phone: "+91 98765 43210",
    },
  },
  {
    id: "agency-002",
    name: "Global Pathways",
    registrationId: "GSTIN29ABCDE1234F1Z5",
    address: "88 Brigade Road",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    status: "active",
    verificationStatus: "verified",
    subscriptionPlan: "enterprise",
    trialEndsAt: null,
    subscriptionEndsAt: "2027-06-30",
    userCount: 42,
    studentCount: 890,
    leadCount: 3200,
    applicationCount: 1120,
    createdAt: "2023-11-02T08:30:00Z",
    admin: {
      firstName: "Priya",
      lastName: "Nair",
      email: "priya@globalpathways.in",
      phone: "+91 91234 56789",
    },
  },
  {
    id: "agency-003",
    name: "Study Abroad Hub",
    registrationId: "U72200MH2021PTC987654",
    address: "5 Linking Road",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    status: "suspended",
    verificationStatus: "verified",
    subscriptionPlan: "starter",
    trialEndsAt: null,
    subscriptionEndsAt: "2025-08-15",
    userCount: 8,
    studentCount: 95,
    leadCount: 410,
    applicationCount: 120,
    createdAt: "2025-01-20T14:00:00Z",
    admin: {
      firstName: "Amit",
      lastName: "Patel",
      email: "amit@studyabroadhub.com",
      phone: "+91 99887 76655",
    },
  },
  {
    id: "agency-004",
    name: "Visa Vista",
    registrationId: "U74999DL2024PTC445566",
    address: "22 Connaught Place",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    status: "pending_verification",
    verificationStatus: "pending",
    subscriptionPlan: "trial",
    trialEndsAt: "2026-07-15",
    subscriptionEndsAt: null,
    userCount: 3,
    studentCount: 12,
    leadCount: 48,
    applicationCount: 5,
    createdAt: "2026-05-28T09:15:00Z",
    admin: {
      firstName: "Neha",
      lastName: "Gupta",
      email: "neha@visavista.in",
      phone: "+91 98700 11223",
    },
  },
  {
    id: "agency-005",
    name: "EduBridge Overseas",
    registrationId: "GSTIN07XYZAB5678C1D2",
    address: "Plot 7, Sector 18",
    city: "Noida",
    state: "Uttar Pradesh",
    country: "India",
    status: "inactive",
    verificationStatus: "rejected",
    subscriptionPlan: "trial",
    trialEndsAt: "2026-04-01",
    subscriptionEndsAt: null,
    userCount: 2,
    studentCount: 0,
    leadCount: 15,
    applicationCount: 0,
    createdAt: "2026-02-10T11:45:00Z",
    admin: {
      firstName: "Karan",
      lastName: "Singh",
      email: "karan@edubridge.com",
      phone: "+91 90000 12345",
    },
  },
];
