import type { Course, University } from "@/modules/universities/universities.types";

export const SEED_UNIVERSITIES: University[] = [
  {
    id: "ucd",
    name: "University College Dublin",
    shortName: "UCD",
    country: "Ireland",
    countryCode: "IE",
    city: "Dublin",
    flag: "🇮🇪",
    founded: 1854,
    website: "ucd.ie",
    qsRank: 201,
    about:
      "Ireland's largest research-intensive university, UCD is ranked among Europe's leading universities. Located 5 km from Dublin city centre, it offers a vibrant campus with 33,000+ students from 150 countries. Strong industry links with multinationals based in Dublin — Google, Facebook, LinkedIn, Pfizer.",
    trackRecord: {
      studentsEnrolled: 28,
      visasApproved: 26,
      visaSuccessRate: 92.8,
      avgApplicationDays: 18,
      avgCommission: "₹65,000",
    },
    links: [
      { label: "UCD International Admissions", url: "#" },
      { label: "Scholarship Guide 2025", url: "#" },
      { label: "Accommodation Portal", url: "#" },
      { label: "Agent Contact: John Murphy", url: "#" },
    ],
    internalNotes:
      "Strong partner. Agent John Murphy responds within 24h. Preferred for Dublin placements. Document submission via portal only — no email submissions.",
    generalRequirements: [
      {
        id: "degree",
        label: "Bachelor's degree (2:1 or above)",
        detail: "Equivalent: 60% Indian university",
        status: "met",
        studentNote: "Rohan: 78.4% ✓",
      },
      {
        id: "ielts",
        label: "IELTS 6.5 overall (no band below 6.0)",
        detail: "Some courses require 7.0 per band — verify",
        status: "warn",
        studentNote: "Rohan: 7.0 (W/S 6.5)",
      },
      {
        id: "background",
        label: "Relevant undergraduate degree",
        status: "met",
        studentNote: "B.Tech CS ✓",
      },
      {
        id: "lor",
        label: "2 Letters of Recommendation",
        status: "warn",
        studentNote: "Not collected yet",
      },
    ],
  },
  {
    id: "manchester",
    name: "University of Manchester",
    shortName: "UoM",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Manchester",
    flag: "🇬🇧",
    founded: 1824,
    website: "manchester.ac.uk",
    qsRank: 28,
    about:
      "A world-leading Russell Group university in the heart of Manchester, known for research excellence and strong graduate employability across engineering, sciences, and business.",
    trackRecord: {
      studentsEnrolled: 19,
      visasApproved: 18,
      visaSuccessRate: 94.7,
      avgApplicationDays: 21,
      avgCommission: "₹58,000",
    },
    links: [
      { label: "International Admissions", url: "#" },
      { label: "Scholarships", url: "#" },
    ],
    internalNotes: "Competitive intake. Allow 3–4 weeks for offer letters.",
    generalRequirements: [
      {
        id: "degree",
        label: "Bachelor's degree (2:1 or above)",
        status: "met",
        studentNote: "Rohan: 78.4% ✓",
      },
      {
        id: "ielts",
        label: "IELTS 6.5 overall",
        status: "met",
        studentNote: "Rohan: 7.0 ✓",
      },
    ],
  },
  {
    id: "nci",
    name: "National College of Ireland",
    shortName: "NCI",
    country: "Ireland",
    countryCode: "IE",
    city: "Dublin",
    flag: "🇮🇪",
    founded: 1951,
    website: "ncirl.ie",
    about:
      "A career-focused college in Dublin's IFSC district, offering practical postgraduate programmes with strong industry placement support.",
    trackRecord: {
      studentsEnrolled: 14,
      visasApproved: 14,
      visaSuccessRate: 100,
      avgApplicationDays: 12,
      avgCommission: "₹42,000",
    },
    links: [{ label: "NCI International", url: "#" }],
    internalNotes: "Fast turnaround on offers. Good value option for Dublin.",
    generalRequirements: [
      {
        id: "degree",
        label: "Bachelor's degree (60%+)",
        status: "met",
        studentNote: "Rohan: 78.4% ✓",
      },
      {
        id: "ielts",
        label: "IELTS 6.0 overall",
        status: "met",
        studentNote: "Rohan: 7.0 ✓",
      },
    ],
  },
  {
    id: "imperial",
    name: "Imperial College London",
    shortName: "Imperial",
    country: "United Kingdom",
    countryCode: "GB",
    city: "London",
    flag: "🇬🇧",
    founded: 1907,
    website: "imperial.ac.uk",
    qsRank: 6,
    about:
      "A world top-10 science and technology university in London, renowned for engineering, computing, and AI research with exceptional graduate outcomes.",
    trackRecord: {
      studentsEnrolled: 6,
      visasApproved: 5,
      visaSuccessRate: 83.3,
      avgApplicationDays: 28,
      avgCommission: "₹95,000",
    },
    links: [{ label: "Imperial Postgraduate Admissions", url: "#" }],
    internalNotes: "Highly selective. Early applications strongly recommended.",
    generalRequirements: [
      {
        id: "degree",
        label: "First-class honours degree",
        status: "warn",
        studentNote: "Rohan: 78.4% — borderline",
      },
      {
        id: "ielts",
        label: "IELTS 7.0 in each band",
        status: "miss",
        studentNote: "Rohan W/S: 6.5",
      },
    ],
  },
  {
    id: "melbourne",
    name: "University of Melbourne",
    shortName: "Melbourne",
    country: "Australia",
    countryCode: "AU",
    city: "Melbourne",
    flag: "🇦🇺",
    founded: 1853,
    website: "unimelb.edu.au",
    qsRank: 13,
    about:
      "A leading Australian research university known for data science, engineering, and strong graduate employability.",
    trackRecord: {
      studentsEnrolled: 11,
      visasApproved: 10,
      visaSuccessRate: 90.9,
      avgApplicationDays: 24,
      avgCommission: "₹70,000",
    },
    links: [{ label: "Melbourne International Admissions", url: "#" }],
    internalNotes: "Feb intake popular with Indian students.",
    generalRequirements: [
      {
        id: "degree",
        label: "Bachelor's degree (65%+)",
        status: "met",
        studentNote: "Rohan: 78.4% ✓",
      },
      {
        id: "ielts",
        label: "IELTS 6.5 overall",
        status: "met",
        studentNote: "Rohan: 7.0 ✓",
      },
    ],
  },
  {
    id: "utoronto",
    name: "University of Toronto",
    shortName: "UofT",
    country: "Canada",
    countryCode: "CA",
    city: "Toronto",
    flag: "🇨🇦",
    founded: 1827,
    website: "utoronto.ca",
    qsRank: 21,
    about:
      "Canada's top-ranked university with strong computer science and analytics programmes.",
    trackRecord: {
      studentsEnrolled: 9,
      visasApproved: 8,
      visaSuccessRate: 88.9,
      avgApplicationDays: 26,
      avgCommission: "₹75,000",
    },
    links: [{ label: "UofT Graduate Admissions", url: "#" }],
    internalNotes: "Competitive. Strong SOP required.",
    generalRequirements: [
      {
        id: "degree",
        label: "Bachelor's degree (75%+)",
        status: "met",
        studentNote: "Rohan: 78.4% ✓",
      },
      {
        id: "ielts",
        label: "IELTS 7.0 overall",
        status: "met",
        studentNote: "Rohan: 7.0 ✓",
      },
    ],
  },
];

export const SEED_COURSES: Course[] = [
  {
    id: "ucd-msc-ds",
    universityId: "ucd",
    name: "MSc Data Science",
    level: "masters",
    levelLabel: "Postgraduate Masters",
    intakes: ["Sep 2025", "Jan 2026"],
    duration: "1 year",
    tuitionLakhs: 24.5,
    ieltsMin: 6.5,
    ieltsPerBand: 6.5,
    ieltsLabel: "IELTS 6.5+",
    applicationFee: "₹8,500",
    deadline: "Mar 31",
    eligibilityStatus: "partial",
    eligibilityPercent: 88,
    eligibilityWarning: "⚠ W/S 6.5 risk",
    alreadyShortlisted: true,
    pendingApplications: 2,
    curriculum: {
      semester1: [
        "Statistical Machine Learning",
        "Data Engineering & Pipelines",
        "Business Analytics Foundations",
        "Programming for Data Science (Python/R)",
      ],
      semester2: [
        "Deep Learning & Neural Networks",
        "NLP & Text Analytics",
        "Research Methods",
        "Capstone Project (12 weeks)",
      ],
    },
    requirements: [
      {
        id: "degree",
        label: "Bachelor's degree",
        detail: "B.Tech CS, BITS Pilani, 78.4%",
        status: "met",
        statusLabel: "Met",
      },
      {
        id: "ielts-overall",
        label: "IELTS Overall 6.5",
        detail: "Rohan: 7.0 overall",
        status: "met",
        statusLabel: "Met",
      },
      {
        id: "ielts-band",
        label: "IELTS per band 6.5 min",
        detail:
          "W = 6.5, S = 6.5. Some courses require 7.0 per band — contact admissions for clarity.",
        status: "warn",
        statusLabel: "⚠ Verify",
      },
      {
        id: "background",
        label: "Relevant UG background",
        detail: "CS degree matches",
        status: "met",
        statusLabel: "Met",
      },
      {
        id: "lor",
        label: "2× LOR",
        detail: "Not yet collected",
        status: "miss",
        statusLabel: "Missing",
      },
    ],
    keyDates: {
      applicationDeadline: "Mar 31, 2025",
      rollingAdmissions: true,
      courseStart: "Sep 8, 2025",
      courseEnd: "Aug 2026",
      pgwpEligible: "N/A (Ireland)",
    },
    fees: {
      tuitionPerYear: "₹24,50,000/yr",
      applicationFee: "₹8,500",
      livingCosts: "~₹12L/yr",
      scholarship: "Global Excellence",
      scholarshipNote:
        "Global Excellence Award: up to €3,000 for high-achieving students. Automatic with offer.",
    },
    ourData: {
      studentsSent: 7,
      accepted: 6,
      visaApproved: 6,
      avgCommission: "₹72,000",
    },
  },
  {
    id: "ucd-msc-cs",
    universityId: "ucd",
    name: "MSc Computer Science",
    level: "masters",
    levelLabel: "Postgraduate Masters",
    intakes: ["Sep 2025"],
    duration: "1 year",
    tuitionLakhs: 26.0,
    ieltsMin: 6.5,
    ieltsLabel: "IELTS 6.5",
    applicationFee: "₹8,500",
    deadline: "Mar 31",
    eligibilityStatus: "eligible",
    eligibilityPercent: 92,
    curriculum: {
      semester1: ["Advanced Algorithms", "Software Engineering", "Distributed Systems"],
      semester2: ["Machine Learning", "Cloud Computing", "Research Project"],
    },
    requirements: [],
    keyDates: {
      applicationDeadline: "Mar 31, 2025",
      rollingAdmissions: true,
      courseStart: "Sep 8, 2025",
      courseEnd: "Aug 2026",
      pgwpEligible: "N/A (Ireland)",
    },
    fees: {
      tuitionPerYear: "₹26,00,000/yr",
      applicationFee: "₹8,500",
      livingCosts: "~₹12L/yr",
    },
    ourData: { studentsSent: 5, accepted: 5, visaApproved: 5, avgCommission: "₹70,000" },
  },
  {
    id: "ucd-msc-ba",
    universityId: "ucd",
    name: "MSc Business Analytics",
    level: "masters",
    levelLabel: "Postgraduate Masters",
    intakes: ["Sep 2025"],
    duration: "1 year",
    tuitionLakhs: 22.0,
    ieltsMin: 7.0,
    ieltsPerBand: 7.0,
    ieltsLabel: "IELTS 7.0 each",
    applicationFee: "₹8,500",
    deadline: "Mar 31",
    eligibilityStatus: "not-eligible",
    eligibilityHint: "Requires IELTS 7.0 in each band.",
    curriculum: { semester1: [], semester2: [] },
    requirements: [],
    keyDates: {
      applicationDeadline: "Mar 31, 2025",
      rollingAdmissions: false,
      courseStart: "Sep 8, 2025",
      courseEnd: "Aug 2026",
      pgwpEligible: "N/A (Ireland)",
    },
    fees: {
      tuitionPerYear: "₹22,00,000/yr",
      applicationFee: "₹8,500",
      livingCosts: "~₹12L/yr",
    },
    ourData: { studentsSent: 2, accepted: 1, visaApproved: 1, avgCommission: "₹55,000" },
  },
  {
    id: "ucd-be-ce",
    universityId: "ucd",
    name: "BE Computer Engineering",
    level: "undergraduate",
    levelLabel: "Undergraduate",
    intakes: ["Sep 2025"],
    duration: "4 years",
    tuitionLakhs: 18.5,
    ieltsMin: 6.0,
    ieltsLabel: "IELTS 6.0",
    applicationFee: "₹6,500",
    deadline: "May 15",
    eligibilityStatus: "eligible",
    eligibilityPercent: 100,
    curriculum: { semester1: [], semester2: [] },
    requirements: [],
    keyDates: {
      applicationDeadline: "May 15, 2025",
      rollingAdmissions: false,
      courseStart: "Sep 8, 2025",
      courseEnd: "Aug 2029",
      pgwpEligible: "N/A (Ireland)",
    },
    fees: {
      tuitionPerYear: "₹18,50,000/yr",
      applicationFee: "₹6,500",
      livingCosts: "~₹12L/yr",
    },
    ourData: { studentsSent: 1, accepted: 1, visaApproved: 1, avgCommission: "₹45,000" },
  },
  {
    id: "manchester-msc-acs",
    universityId: "manchester",
    name: "MSc Advanced Computer Science",
    level: "masters",
    levelLabel: "Postgraduate Masters",
    intakes: ["Sep 2025"],
    duration: "1 year",
    tuitionLakhs: 31.8,
    ieltsMin: 6.5,
    ieltsLabel: "IELTS 6.5+",
    applicationFee: "₹10,000",
    deadline: "Apr 30",
    eligibilityStatus: "eligible",
    eligibilityPercent: 95,
    curriculum: {
      semester1: ["Advanced Machine Learning", "Computer Vision", "Formal Methods"],
      semester2: ["NLP", "Robotics", "Dissertation"],
    },
    requirements: [],
    keyDates: {
      applicationDeadline: "Apr 30, 2025",
      rollingAdmissions: false,
      courseStart: "Sep 22, 2025",
      courseEnd: "Sep 2026",
      pgwpEligible: "N/A (UK)",
    },
    fees: {
      tuitionPerYear: "₹31,80,000/yr",
      applicationFee: "₹10,000",
      livingCosts: "~₹14L/yr",
    },
    ourData: { studentsSent: 4, accepted: 4, visaApproved: 4, avgCommission: "₹68,000" },
  },
  {
    id: "nci-msc-da",
    universityId: "nci",
    name: "MSc Data Analytics",
    level: "masters",
    levelLabel: "Postgraduate Masters",
    intakes: ["Jan 2026"],
    duration: "1 year",
    tuitionLakhs: 14.2,
    ieltsMin: 6.0,
    ieltsLabel: "IELTS 6.0+",
    applicationFee: "₹5,500",
    deadline: "Rolling",
    eligibilityStatus: "eligible",
    eligibilityPercent: 100,
    alreadyShortlisted: true,
    curriculum: {
      semester1: ["Data Mining", "Statistics for Analytics", "SQL & Databases"],
      semester2: ["Predictive Modelling", "Visualisation", "Industry Project"],
    },
    requirements: [],
    keyDates: {
      applicationDeadline: "Rolling",
      rollingAdmissions: true,
      courseStart: "Jan 12, 2026",
      courseEnd: "Dec 2026",
      pgwpEligible: "N/A (Ireland)",
    },
    fees: {
      tuitionPerYear: "₹14,20,000/yr",
      applicationFee: "₹5,500",
      livingCosts: "~₹12L/yr",
    },
    ourData: { studentsSent: 6, accepted: 6, visaApproved: 6, avgCommission: "₹48,000" },
  },
  {
    id: "imperial-msc-ai",
    universityId: "imperial",
    name: "MSc Artificial Intelligence",
    level: "masters",
    levelLabel: "Postgraduate Masters",
    intakes: ["Sep 2025"],
    duration: "1 year",
    tuitionLakhs: 42.0,
    ieltsMin: 7.0,
    ieltsPerBand: 7.0,
    ieltsLabel: "IELTS 7.0 each band",
    applicationFee: "₹12,000",
    deadline: "Jan 15",
    eligibilityStatus: "not-eligible",
    eligibilityHint:
      "Requires IELTS 7.0 in each band. Rohan's W/S = 6.5 — does not qualify.",
    curriculum: {
      semester1: ["Foundations of AI", "Deep Learning", "Probabilistic Reasoning"],
      semester2: ["Reinforcement Learning", "AI Ethics", "Research Project"],
    },
    requirements: [],
    keyDates: {
      applicationDeadline: "Jan 15, 2025",
      rollingAdmissions: false,
      courseStart: "Oct 1, 2025",
      courseEnd: "Sep 2026",
      pgwpEligible: "N/A (UK)",
    },
    fees: {
      tuitionPerYear: "₹42,00,000/yr",
      applicationFee: "₹12,000",
      livingCosts: "~₹18L/yr",
    },
    ourData: { studentsSent: 2, accepted: 1, visaApproved: 1, avgCommission: "₹90,000" },
  },
  {
    id: "melbourne-msc-ds",
    universityId: "melbourne",
    name: "Master of Data Science",
    level: "masters",
    levelLabel: "Postgraduate Masters",
    intakes: ["Feb 2026"],
    duration: "2 years",
    tuitionLakhs: 28.0,
    ieltsMin: 6.5,
    ieltsLabel: "IELTS 6.5+",
    applicationFee: "₹9,500",
    deadline: "Oct 31",
    eligibilityStatus: "eligible",
    eligibilityPercent: 95,
    curriculum: {
      semester1: ["Statistics for Data Science", "Programming for Data Science"],
      semester2: ["Machine Learning", "Big Data Systems"],
    },
    requirements: [],
    keyDates: {
      applicationDeadline: "Oct 31, 2025",
      rollingAdmissions: false,
      courseStart: "Feb 24, 2026",
      courseEnd: "Feb 2028",
      pgwpEligible: "Yes (Australia)",
    },
    fees: {
      tuitionPerYear: "₹28,00,000/yr",
      applicationFee: "₹9,500",
      livingCosts: "~₹15L/yr",
    },
    ourData: { studentsSent: 3, accepted: 3, visaApproved: 3, avgCommission: "₹68,000" },
  },
  {
    id: "utoronto-msc-cs",
    universityId: "utoronto",
    name: "MSc Computer Science",
    level: "masters",
    levelLabel: "Postgraduate Masters",
    intakes: ["Sep 2025", "Jan 2026"],
    duration: "1.5 years",
    tuitionLakhs: 32.5,
    ieltsMin: 7.0,
    ieltsLabel: "IELTS 7.0+",
    applicationFee: "₹11,000",
    deadline: "Apr 15",
    eligibilityStatus: "partial",
    eligibilityPercent: 75,
    curriculum: {
      semester1: ["Advanced Algorithms", "Machine Learning"],
      semester2: ["Distributed Systems", "Thesis"],
    },
    requirements: [],
    keyDates: {
      applicationDeadline: "Apr 15, 2025",
      rollingAdmissions: false,
      courseStart: "Sep 2, 2025",
      courseEnd: "Apr 2027",
      pgwpEligible: "Yes (Canada)",
    },
    fees: {
      tuitionPerYear: "₹32,50,000/yr",
      applicationFee: "₹11,000",
      livingCosts: "~₹16L/yr",
    },
    ourData: { studentsSent: 2, accepted: 2, visaApproved: 2, avgCommission: "₹80,000" },
  },
];

