import { ROLES, type RoleKey } from "@/config/roles/roles";

/**
 * Permission strings returned by the backend auth service.
 * Clean DOMAIN_ACTION taxonomy (see docs/role-consolidation-plan.md). Record-level
 * visibility (own/team/all) is the role's scope_level, not a permission.
 */
export const PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  LEAD_VIEW: "LEAD_VIEW",
  LEAD_CREATE: "LEAD_CREATE",
  LEAD_EDIT: "LEAD_EDIT",
  LEAD_DELETE: "LEAD_DELETE",
  LEAD_ASSIGN: "LEAD_ASSIGN",
  LEAD_IMPORT: "LEAD_IMPORT",
  LEAD_CONVERT: "LEAD_CONVERT",

  APPLICATION_VIEW: "APPLICATION_VIEW",
  APPLICATION_CREATE: "APPLICATION_CREATE",
  APPLICATION_EDIT: "APPLICATION_EDIT",
  APPLICATION_CLOSE: "APPLICATION_CLOSE",

  STUDENT_VIEW: "STUDENT_VIEW",
  STUDENT_EDIT: "STUDENT_EDIT",
  STUDENT_DOCS: "STUDENT_DOCS",

  UNIVERSITY_VIEW: "UNIVERSITY_VIEW",
  UNIVERSITY_MANAGE: "UNIVERSITY_MANAGE",

  ACTIVITY_VIEW: "ACTIVITY_VIEW",
  ACTIVITY_LOG: "ACTIVITY_LOG",

  TASK_VIEW: "TASK_VIEW",
  TASK_CREATE: "TASK_CREATE",
  TASK_COMPLETE: "TASK_COMPLETE",

  USER_VIEW: "USER_VIEW",
  USER_MANAGE: "USER_MANAGE",
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_MANAGE: "ROLE_MANAGE",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS] | string;

const allPermissions = Object.values(PERMISSIONS);

/**
 * Fallback map used only when the backend doesn't return a permission list.
 * The backend is authoritative; this mirrors the taxonomy matrix.
 */
export const ROLE_PERMISSION_MAP: Record<RoleKey, PermissionKey[]> = {
  [ROLES.SUPER_ADMIN]: allPermissions,
  [ROLES.AGENCY_ADMIN]: allPermissions,
  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.LEAD_VIEW, PERMISSIONS.LEAD_CREATE, PERMISSIONS.LEAD_EDIT,
    PERMISSIONS.LEAD_DELETE, PERMISSIONS.LEAD_ASSIGN, PERMISSIONS.LEAD_IMPORT, PERMISSIONS.LEAD_CONVERT,
    PERMISSIONS.APPLICATION_VIEW, PERMISSIONS.APPLICATION_CREATE, PERMISSIONS.APPLICATION_EDIT, PERMISSIONS.APPLICATION_CLOSE,
    PERMISSIONS.STUDENT_VIEW, PERMISSIONS.STUDENT_EDIT, PERMISSIONS.STUDENT_DOCS,
    PERMISSIONS.UNIVERSITY_VIEW, PERMISSIONS.UNIVERSITY_MANAGE,
    PERMISSIONS.ACTIVITY_VIEW, PERMISSIONS.ACTIVITY_LOG,
    PERMISSIONS.TASK_VIEW, PERMISSIONS.TASK_CREATE, PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.USER_VIEW,
  ],
  [ROLES.COUNSELLOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.LEAD_VIEW, PERMISSIONS.LEAD_CREATE, PERMISSIONS.LEAD_EDIT,
    PERMISSIONS.LEAD_IMPORT, PERMISSIONS.LEAD_CONVERT,
    PERMISSIONS.APPLICATION_VIEW, PERMISSIONS.APPLICATION_CREATE, PERMISSIONS.APPLICATION_EDIT,
    PERMISSIONS.STUDENT_VIEW, PERMISSIONS.STUDENT_EDIT, PERMISSIONS.STUDENT_DOCS,
    PERMISSIONS.UNIVERSITY_VIEW,
    PERMISSIONS.ACTIVITY_VIEW, PERMISSIONS.ACTIVITY_LOG,
    PERMISSIONS.TASK_VIEW, PERMISSIONS.TASK_CREATE, PERMISSIONS.TASK_COMPLETE,
  ],
  [ROLES.LEAD_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.LEAD_VIEW, PERMISSIONS.LEAD_CREATE, PERMISSIONS.LEAD_EDIT,
    PERMISSIONS.LEAD_ASSIGN, PERMISSIONS.LEAD_IMPORT,
    PERMISSIONS.UNIVERSITY_VIEW,
    PERMISSIONS.ACTIVITY_VIEW, PERMISSIONS.ACTIVITY_LOG,
    PERMISSIONS.TASK_VIEW, PERMISSIONS.TASK_CREATE, PERMISSIONS.TASK_COMPLETE,
  ],
};

export function getPermissionsForRoles(roles: RoleKey[]) {
  return Array.from(new Set(roles.flatMap((role) => ROLE_PERMISSION_MAP[role] ?? [])));
}
