export const API_CONFIG = {
  auth: "/auth",
  users: "/users",
  roles: "/roles",
  leads: "/leads",
  activities: "/activities",
  tasks: "/tasks",
  applications: "/applications",
  students: "/students",
  dashboard: "/dashboard",
  universities: "/universities",
  adminUniversities: "/admin/universities",
  adminCourses: "/admin/courses",
  adminRequirements: "/admin/requirements",
  courses: "/courses",
  stageTemplates: "/stage-templates",
} as const;
